# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authentication.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61uthentication.proto\x12\x11server.auth.proto\"%\n\x15\x41uthenticationRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"/\n\x16\x41uthenticationResponse\x12\x15\n\ris_authorized\x18\x01 \x01(\x08\x32~\n\x15\x41uthenticationService\x12\x65\n\x0c\x61uthenticate\x12(.server.auth.proto.AuthenticationRequest\x1a).server.auth.proto.AuthenticationResponse\"\x00\x42\x02P\x01\x62\x06proto3')



_AUTHENTICATIONREQUEST = DESCRIPTOR.message_types_by_name['AuthenticationRequest']
_AUTHENTICATIONRESPONSE = DESCRIPTOR.message_types_by_name['AuthenticationResponse']
AuthenticationRequest = _reflection.GeneratedProtocolMessageType('AuthenticationRequest', (_message.Message,), {
  'DESCRIPTOR' : _AUTHENTICATIONREQUEST,
  '__module__' : 'authentication_pb2'
  # @@protoc_insertion_point(class_scope:server.auth.proto.AuthenticationRequest)
  })
_sym_db.RegisterMessage(AuthenticationRequest)

AuthenticationResponse = _reflection.GeneratedProtocolMessageType('AuthenticationResponse', (_message.Message,), {
  'DESCRIPTOR' : _AUTHENTICATIONRESPONSE,
  '__module__' : 'authentication_pb2'
  # @@protoc_insertion_point(class_scope:server.auth.proto.AuthenticationResponse)
  })
_sym_db.RegisterMessage(AuthenticationResponse)

_AUTHENTICATIONSERVICE = DESCRIPTOR.services_by_name['AuthenticationService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _AUTHENTICATIONREQUEST._serialized_start=43
  _AUTHENTICATIONREQUEST._serialized_end=80
  _AUTHENTICATIONRESPONSE._serialized_start=82
  _AUTHENTICATIONRESPONSE._serialized_end=129
  _AUTHENTICATIONSERVICE._serialized_start=131
  _AUTHENTICATIONSERVICE._serialized_end=257
# @@protoc_insertion_point(module_scope)
